nodeLinker: node-modules
nmHoistingLimits: workspaces

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

packageExtensions:
  typescript@*:
    patchedDependencies:
      "typescript@5.8.3": "patches/typescript@5.8.3.patch"

yarnPath: .yarn/releases/yarn-3.6.1.cjs